DROP TABLE WIKI_PAGE;
CREATE TABLE WIKI_PAGE(
 NAME VARCHAR(100) PRIMARY KEY,
 CONTENT VARCHAR(2000000000),
 UPDATE_TIME TIMESTAMP(1) DEFAULT CURRENT_TIMESTAMP,
 IP VARCHAR(18),
 DELETE_FLAG VARCHAR(1),
 DELETE_KEY VARCHAR(12)
 );
 
 DROP TABLE WIKI_HISTORY;
CREATE TABLE WIKI_HISTORY(
 HISTORY_NUM VARCHAR(100000),
 NAME VARCHAR(100),
 CONTENT VARCHAR(2000000000),
 UPDATE_TIME TIMESTAMP(1) DEFAULT CURRENT_TIMESTAMP,
 IP VARCHAR(18),
 DELETE_FLAG VARCHAR(1),
 DELETE_KEY VARCHAR(12)
 );
 
 
 